# backend/Dockerfile
FROM python:latest
WORKDIR /app
COPY app.py /app
RUN pip install flask
CMD ["python", "app.py"]


# # Use an official Python runtime as a parent image 
# FROM python:3.8-slim 
# # Set the working directory in the container 
# WORKDIR /app 
# # Copy the current directory contents into the container at /app 
# COPY . /app 
# # Install any needed packages specified in requirements.txt 
# # (Skip this step if no external packages are needed) 
# RUN pip install --trusted-host pypi.python.org -r requirements.txt || true 
# Make port 80 available to the outside world 
# EXPOSE 80 
# # Define environment variable 
# ENV NAME World 
# # Run app.py when the container launches 
# CMD ["python", "app.py"]